name: ecommerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  equatable: ^2.0.7
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  path: ^1.9.1
  cloud_firestore: ^6.0.3
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.29.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.4

  # Testing
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  integration_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/